import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactLenis } from 'lenis/react'

const koulen = localFont({
  src: "../public/assets/fonts/koulen-regular.ttf",
  display: "swap",
  variable: "--font-koulen",
});

const pinyonScript = localFont({
  src: "../public/assets/fonts/pinyon-script-regular.ttf",
  display: "swap",
  variable: "--font-pinyon-script",
});

const robotoMono = localFont({
  src: "../public/assets/fonts/roboto-mono-variable.ttf",
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Balazs Otakomaiya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root />
      <body
        className={`${koulen} ${pinyonScript} ${robotoMono} antialiased min-h-lvh h-full w-full relative noise bg-gradient-to-br from-custom-green-400 to-custom-green`}
      >
        <div className="p-6">{children}</div>
      </body>
    </html>
  );
}
