import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const koulen = localFont({
    src: './assets/fonts/koulen-regular.ttf',
    display: 'swap',
})

const pinyonScript = localFont({
    src: './assets/fonts/pinyon-script-regular.ttf',
    display: 'swap',
})

const robotoMono = localFont({
    src: './assets/fonts/roboto-mono-variable.ttf',
    display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${koulen} ${pinyonScript} ${robotoMono} antialiased min-h-lvh h-full w-full relative noise bg-gradient-to-br from-custom-green-400 to-custom-green`}
      >
        {children}
      </body>
    </html>
  );
}
